-- How the demo project (xsfqeepxnmnvlhxwkfnw) was built, and how to rebuild
-- one. Each query below runs READ-ONLY on the real project and returns DDL
-- text; apply that text, in order, to the empty demo project. No rows are
-- copied except the lookup lists: no people, no activity, no files.
--
-- Why not replay supabase/migrations? Early migrations seed people and some
-- fixes were applied directly, so the catalog of the real project is the
-- source of truth. Check the result with ops/schema_fingerprint.sql.
--
-- After step 11: app_config, cron, seed (see docs/ENVIRONMENTS.md).

-- 1. Schema, extensions, enums
--   create schema if not exists private;
--   create extension if not exists pg_net schema extensions;
--   create extension if not exists pg_cron;
select string_agg(format('create type %I.%I as enum (%s);', n.nspname, t.typname,
         (select string_agg(quote_literal(e.enumlabel), ', ' order by e.enumsortorder) from pg_enum e where e.enumtypid = t.oid)), E'\n')
from pg_type t join pg_namespace n on n.oid = t.typnamespace
where t.typtype = 'e' and n.nspname in ('public', 'private');

-- 2. Tables (columns, identity, defaults, not null). Prefix with
--   set search_path = public, extensions;
with cols as (
  select c.oid, n.nspname, c.relname, a.attnum,
    format('%I %s%s%s%s', a.attname, format_type(a.atttypid, a.atttypmod),
      case a.attidentity when 'a' then ' generated always as identity' when 'd' then ' generated by default as identity' else '' end,
      case when d.adbin is not null and a.attidentity = '' and a.attgenerated = '' then ' default ' || pg_get_expr(d.adbin, d.adrelid) else '' end,
      case when a.attnotnull then ' not null' else '' end) def
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
  join pg_attribute a on a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped
  left join pg_attrdef d on d.adrelid = c.oid and d.adnum = a.attnum
  where c.relkind = 'r' and n.nspname in ('public', 'private')
)
select string_agg(format('create table %I.%I (%s);', nspname, relname, defs), E'\n')
from (select nspname, relname, string_agg(def, ', ' order by attnum) defs from cols group by 1, 2) t;

-- 3. Keys and checks, then 4. foreign keys (prefix: set search_path = public;)
select string_agg(format('alter table %I.%I add constraint %I %s;', n.nspname, cl.relname, con.conname, pg_get_constraintdef(con.oid)), E'\n'
         order by n.nspname, cl.relname, con.contype desc, con.conname)
from pg_constraint con join pg_class cl on cl.oid = con.conrelid join pg_namespace n on n.oid = cl.relnamespace
where n.nspname in ('public', 'private') and con.contype in ('p', 'u', 'c', 'x');   -- then contype = 'f'

-- 5. Other indexes
select string_agg(pg_get_indexdef(ix.indexrelid) || ';', E'\n')
from pg_index ix join pg_class cl on cl.oid = ix.indrelid join pg_namespace n on n.oid = cl.relnamespace
where n.nspname in ('public', 'private') and not exists (select 1 from pg_constraint k where k.conindid = ix.indexrelid);

-- 6. Functions (prefix: set check_function_bodies = off;). Large ones one at a time.
with f as materialized (select p.oid from pg_proc p join pg_namespace n on n.oid = p.pronamespace
                        where n.nspname in ('public', 'private') and p.prokind = 'f')
select string_agg(pg_get_functiondef(oid) || ';', E'\n') from f;

-- 7. Views (keeps security_invoker)
select string_agg(format('create or replace view %I.%I%s as %s', n.nspname, c.relname,
         case when c.reloptions is not null then ' with (' || array_to_string(c.reloptions, ', ') || ')' else '' end,
         pg_get_viewdef(c.oid, true)), E'\n')
from pg_class c join pg_namespace n on n.oid = c.relnamespace where c.relkind = 'v' and n.nspname in ('public', 'private');

-- 8. Triggers, including enforce_invitation on auth.users
select string_agg(pg_get_triggerdef(t.oid) || ';', E'\n')
from pg_trigger t join pg_class c on c.oid = t.tgrelid join pg_namespace n on n.oid = c.relnamespace
join pg_proc p on p.oid = t.tgfoid join pg_namespace pn on pn.oid = p.pronamespace
where not t.tgisinternal and pn.nspname in ('public', 'private');

-- 9. RLS on, and every policy (public, private, storage)
select string_agg(format('alter table %I.%I enable row level security;', n.nspname, c.relname), E'\n')
from pg_class c join pg_namespace n on n.oid = c.relnamespace where c.relkind = 'r' and n.nspname in ('public', 'private') and c.relrowsecurity;
select string_agg(format('create policy %I on %I.%I as %s for %s to %s%s%s;', policyname, schemaname, tablename, permissive, cmd,
         array_to_string(roles, ', '),
         case when qual is not null then ' using (' || qual || ')' else '' end,
         case when with_check is not null then ' with check (' || with_check || ')' else '' end), E'\n')
from pg_policies where schemaname in ('public', 'private', 'storage');

-- 10. Grants. New projects grant everything by default; the real project
-- differs only in: profiles (column-level SELECT for authenticated, nothing
-- for anon), public_directory and community_endorsement_scores (no anon),
-- private schema (authenticated usage only) and function EXECUTE. List the
-- function grants with:
select n.nspname || '.' || p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ')',
       has_function_privilege('anon', p.oid, 'EXECUTE') anon, has_function_privilege('authenticated', p.oid, 'EXECUTE') authed
from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname in ('public', 'private') and p.prokind = 'f';

-- 11. Lookup lists, keeping ids (the demo seed refers to them by id)
select 'insert into public.lookup_values (id, category, value) overriding system value values '
       || string_agg(format('(%s,%L,%L)', id, category, value), ',' order by id) || ';'
from public.lookup_values;
