-- Replace the placeholder seed values (0002_seed_lookup_values.sql) with the
-- real, full dropdown lists from Nick's PsychologistCommunity.xlsx spec.
-- No real users exist yet, so a clean truncate + reseed is safe (nothing
-- references the old placeholder ids that would be orphaned).
truncate lookup_values restart identity cascade;

insert into lookup_values (category, value) values
  ('treatment_specialism', 'Addictions'),
  ('treatment_specialism', 'ADHD'),
  ('treatment_specialism', 'Adoption/Foster Care'),
  ('treatment_specialism', 'Aging'),
  ('treatment_specialism', 'Alzheimer’s/Dementia'),
  ('treatment_specialism', 'Anger Management'),
  ('treatment_specialism', 'Anxiety/Panic Disorders'),
  ('treatment_specialism', 'Autism/PDD'),
  ('treatment_specialism', 'Behavioral Problems'),
  ('treatment_specialism', 'Bipolar Disorder'),
  ('treatment_specialism', 'Bullying'),
  ('treatment_specialism', 'Burnout'),
  ('treatment_specialism', 'Career/Employment Concerns'),
  ('treatment_specialism', 'Child Abuse & Neglect'),
  ('treatment_specialism', 'Chronic Illness'),
  ('treatment_specialism', 'Depression'),
  ('treatment_specialism', 'Developmental Disabilities'),
  ('treatment_specialism', 'Disability'),
  ('treatment_specialism', 'Diverse Sexualities / Kink'),
  ('treatment_specialism', 'Domestic Violence'),
  ('treatment_specialism', 'Eating Disorders'),
  ('treatment_specialism', 'Education/Personal Development'),
  ('treatment_specialism', 'Elder Abuse'),
  ('treatment_specialism', 'Family'),
  ('treatment_specialism', 'Firesetting'),
  ('treatment_specialism', 'Forensic'),
  ('treatment_specialism', 'Grief/Loss'),
  ('treatment_specialism', 'Health & Wellness'),
  ('treatment_specialism', 'HIV & AIDS'),
  ('treatment_specialism', 'Hypnosis'),
  ('treatment_specialism', 'Immigration'),
  ('treatment_specialism', 'Infertility'),
  ('treatment_specialism', 'Learning Disabilities'),
  ('treatment_specialism', 'LGBTQ Issues'),
  ('treatment_specialism', 'Life Transitions'),
  ('treatment_specialism', 'Marriage & Divorce'),
  ('treatment_specialism', 'Military'),
  ('treatment_specialism', 'Multicultural Issues'),
  ('treatment_specialism', 'Neuropsychology'),
  ('treatment_specialism', 'Obesity/Weight Loss'),
  ('treatment_specialism', 'Obsessive/Compulsive Disorder'),
  ('treatment_specialism', 'Open Relationships / Consensual Non-monogamy'),
  ('treatment_specialism', 'Pain Management'),
  ('treatment_specialism', 'Parenting Issues'),
  ('treatment_specialism', 'Personality Disorders'),
  ('treatment_specialism', 'Phobias'),
  ('treatment_specialism', 'Physical Illness/Impairment'),
  ('treatment_specialism', 'Pregnancy/Childbirth'),
  ('treatment_specialism', 'Schizophrenia'),
  ('treatment_specialism', 'Self Abuse'),
  ('treatment_specialism', 'Serious Mental Illness'),
  ('treatment_specialism', 'Sexual Abuse/Rape'),
  ('treatment_specialism', 'Sexual Health'),
  ('treatment_specialism', 'Sleep Disorders'),
  ('treatment_specialism', 'Spiritual/Religious'),
  ('treatment_specialism', 'Sport and Exercise'),
  ('treatment_specialism', 'Stress'),
  ('treatment_specialism', 'Suicide'),
  ('treatment_specialism', 'Testing Issues'),
  ('treatment_specialism', 'Tourette''s Disorder'),
  ('treatment_specialism', 'Trauma/PTSD'),
  ('treatment_specialism', 'Violence');

insert into lookup_values (category, value) values
  ('treatment_modality', 'Advocacy'),
  ('treatment_modality', 'Behavioral'),
  ('treatment_modality', 'Behavioral Medicine'),
  ('treatment_modality', 'Coaching'),
  ('treatment_modality', 'Cognitive/Behavioral'),
  ('treatment_modality', 'Contemplative'),
  ('treatment_modality', 'Crisis Intervention'),
  ('treatment_modality', 'Critical Incident Stress Debriefing (CISD)'),
  ('treatment_modality', 'Dialectical Behavior Therapy'),
  ('treatment_modality', 'Education Consultation'),
  ('treatment_modality', 'Evaluation/Diagnostic'),
  ('treatment_modality', 'Existential Psychotherapy'),
  ('treatment_modality', 'Expressive Therapy'),
  ('treatment_modality', 'Feminist'),
  ('treatment_modality', 'Focusing'),
  ('treatment_modality', 'Forensic Evaluation'),
  ('treatment_modality', 'Geriatric Consultation'),
  ('treatment_modality', 'Gestalt'),
  ('treatment_modality', 'Group Psychotherapy'),
  ('treatment_modality', 'Humanistic'),
  ('treatment_modality', 'Information and Referral'),
  ('treatment_modality', 'Intervention (Alcohol, Drug, Gambling Addiction, etc.)'),
  ('treatment_modality', 'Long-Term'),
  ('treatment_modality', 'Meditation/Relaxation'),
  ('treatment_modality', 'Neuropsychological Testing or Consultation'),
  ('treatment_modality', 'Outreach'),
  ('treatment_modality', 'Parent Guidance'),
  ('treatment_modality', 'Play Therapy'),
  ('treatment_modality', 'Prevention'),
  ('treatment_modality', 'Psychoanalysis'),
  ('treatment_modality', 'Psychodrama'),
  ('treatment_modality', 'Psychodynamic'),
  ('treatment_modality', 'Psycho-Educational'),
  ('treatment_modality', 'Psychological Testing and Evaluation'),
  ('treatment_modality', 'Relational'),
  ('treatment_modality', 'Short-Term (Brief Treatment)'),
  ('treatment_modality', 'Social Support'),
  ('treatment_modality', 'Systemic'),
  ('treatment_modality', 'Transactional Analysis (TA)'),
  ('treatment_modality', 'Transpersonal Psychology');

insert into lookup_values (category, value) values
  ('insurance', 'AETNA Health, Inc.'),
  ('insurance', 'AETNA Inc. (Open Choice)'),
  ('insurance', 'American LIFECARE, Inc.'),
  ('insurance', 'BestCare, Inc.'),
  ('insurance', 'Blue Cross and Blue Shield (HMO)'),
  ('insurance', 'BlueCross BlueShield (GroupCare)'),
  ('insurance', 'CIGNA HealthCare (PPO)'),
  ('insurance', 'Coventry Health Care'),
  ('insurance', 'Coventry Health Care (PPO)'),
  ('insurance', 'FARA PPO Network'),
  ('insurance', 'Health Plus'),
  ('insurance', 'Horizon Behavioral Services'),
  ('insurance', 'Magellan Behavioral Health'),
  ('insurance', 'Managed Health Network'),
  ('insurance', 'Medicaid'),
  ('insurance', 'Medicare'),
  ('insurance', 'Ochsner Health Plan'),
  ('insurance', 'PacifiCare Behavioral Health'),
  ('insurance', 'PPOplus, LLC'),
  ('insurance', 'Private Healthcare Systems'),
  ('insurance', 'Tenet Choices, Inc.'),
  ('insurance', 'Tenet Choices, Inc. (Medicare PPO)'),
  ('insurance', 'United Behavioral Health'),
  ('insurance', 'United Healthcare'),
  ('insurance', 'United HealthCare (Options PPO)'),
  ('insurance', 'Vantage Health Plan, Inc.'),
  ('insurance', 'Other'),
  ('insurance', 'Out of Pocket Pay');

insert into lookup_values (category, value) values
  ('language', 'English'),
  ('language', 'Afrikaans'),
  ('language', 'Albanian'),
  ('language', 'American Sign Language (ASL)'),
  ('language', 'Arabic'),
  ('language', 'Armenian'),
  ('language', 'Bengali'),
  ('language', 'Cambodian'),
  ('language', 'Cantonese'),
  ('language', 'Chinese'),
  ('language', 'Creole'),
  ('language', 'Croatian'),
  ('language', 'Czech'),
  ('language', 'Dakota'),
  ('language', 'Danish'),
  ('language', 'Dineh'),
  ('language', 'Dutch'),
  ('language', 'Farsi'),
  ('language', 'Filipino'),
  ('language', 'Finnish'),
  ('language', 'French'),
  ('language', 'German'),
  ('language', 'Georgian'),
  ('language', 'Greek'),
  ('language', 'Gujarati'),
  ('language', 'Haitian'),
  ('language', 'Hawaiian'),
  ('language', 'Hebrew'),
  ('language', 'Hindi'),
  ('language', 'Hopi'),
  ('language', 'Hungarian'),
  ('language', 'Indian'),
  ('language', 'Italian'),
  ('language', 'Japanese'),
  ('language', 'Kannada'),
  ('language', 'Khmer'),
  ('language', 'Korean'),
  ('language', 'Lakota'),
  ('language', 'Lebanese'),
  ('language', 'Lithuanian'),
  ('language', 'Mandarin'),
  ('language', 'Marathi'),
  ('language', 'Norwegian'),
  ('language', 'Persian'),
  ('language', 'Polish'),
  ('language', 'Portuguese'),
  ('language', 'Punjabi'),
  ('language', 'Romanian'),
  ('language', 'Russian'),
  ('language', 'Serbian'),
  ('language', 'Spanish'),
  ('language', 'Swahili'),
  ('language', 'Swedish'),
  ('language', 'Tagalog'),
  ('language', 'Taiwanese'),
  ('language', 'Tamil'),
  ('language', 'Telugu'),
  ('language', 'Thai'),
  ('language', 'Turkish'),
  ('language', 'Ukrainian'),
  ('language', 'Urdu'),
  ('language', 'Vietnamese'),
  ('language', 'Yiddish');

insert into lookup_values (category, value) values
  ('session_type', 'Face to Face'),
  ('session_type', 'Virtual');

insert into lookup_values (category, value) values
  ('age_group_specialism', 'Seniors'),
  ('age_group_specialism', 'Adults'),
  ('age_group_specialism', 'Young Adults'),
  ('age_group_specialism', 'Adolescents'),
  ('age_group_specialism', 'Children');

insert into lookup_values (category, value) values
  ('sexual_orientation_specialism', 'Heterosexual'),
  ('sexual_orientation_specialism', 'Gay'),
  ('sexual_orientation_specialism', 'Lesbian'),
  ('sexual_orientation_specialism', 'Bisexual');

insert into lookup_values (category, value) values
  ('ethnicity', 'White (Caucasian)'),
  ('ethnicity', 'Black (African American)'),
  ('ethnicity', 'Native American'),
  ('ethnicity', 'Alaska Native'),
  ('ethnicity', 'Asian'),
  ('ethnicity', 'Pacific Islander'),
  ('ethnicity', 'Hispanic (Latino)');

insert into lookup_values (category, value) values
  ('gender_identity', 'Male'),
  ('gender_identity', 'Female'),
  ('gender_identity', 'Transgender'),
  ('gender_identity', 'Gender-Queer/Non-Conforming');

insert into lookup_values (category, value) values
  ('sex', 'Male'),
  ('sex', 'Female'),
  ('sex', 'Non-binary');

insert into lookup_values (category, value) values
  ('us_state', 'Alabama'),
  ('us_state', 'Alaska'),
  ('us_state', 'Arizona'),
  ('us_state', 'Arkansas'),
  ('us_state', 'California'),
  ('us_state', 'Colorado'),
  ('us_state', 'Connecticut'),
  ('us_state', 'Delaware'),
  ('us_state', 'Florida'),
  ('us_state', 'Georgia'),
  ('us_state', 'Hawaii'),
  ('us_state', 'Idaho'),
  ('us_state', 'Illinois'),
  ('us_state', 'Indiana'),
  ('us_state', 'Iowa'),
  ('us_state', 'Kansas'),
  ('us_state', 'Kentucky'),
  ('us_state', 'Louisiana'),
  ('us_state', 'Maine'),
  ('us_state', 'Maryland'),
  ('us_state', 'Massachusetts'),
  ('us_state', 'Michigan'),
  ('us_state', 'Minnesota'),
  ('us_state', 'Mississippi'),
  ('us_state', 'Missouri'),
  ('us_state', 'Montana'),
  ('us_state', 'Nebraska'),
  ('us_state', 'Nevada'),
  ('us_state', 'New Hampshire'),
  ('us_state', 'New Jersey'),
  ('us_state', 'New Mexico'),
  ('us_state', 'New York'),
  ('us_state', 'North Carolina'),
  ('us_state', 'North Dakota'),
  ('us_state', 'Ohio'),
  ('us_state', 'Oklahoma'),
  ('us_state', 'Oregon'),
  ('us_state', 'Pennsylvania'),
  ('us_state', 'Rhode Island'),
  ('us_state', 'South Carolina'),
  ('us_state', 'South Dakota'),
  ('us_state', 'Tennessee'),
  ('us_state', 'Texas'),
  ('us_state', 'Utah'),
  ('us_state', 'Vermont'),
  ('us_state', 'Virginia'),
  ('us_state', 'Washington'),
  ('us_state', 'West Virginia'),
  ('us_state', 'Wisconsin'),
  ('us_state', 'Wyoming');
