-- Personal activity feed: a lightweight append-only log of "something
-- happened that might interest other members" events, filtered per-viewer
-- by specialism/state overlap at query time (no per-viewer fan-out table).
create table public.activity_events (
  id bigint generated by default as identity primary key,
  event_type text not null check (event_type in ('new_member', 'town_hall_post', 'document_upload')),
  actor_profile_id uuid not null references public.profiles(id) on delete cascade,
  actor_name text not null,
  specialism_ids bigint[] not null default '{}',
  state text,
  summary text not null,
  metadata jsonb not null default '{}',
  created_at timestamptz not null default now()
);

create index activity_events_created_at_idx on public.activity_events (created_at desc);
create index activity_events_specialism_ids_idx on public.activity_events using gin (specialism_ids);

alter table public.activity_events enable row level security;

create policy "verified users can read activity events"
  on public.activity_events for select
  using (exists (
    select 1 from public.profiles
    where profiles.id = (select auth.uid()) and profiles.verification_status = 'verified'
  ));

create policy "verified users can log their own activity events"
  on public.activity_events for insert
  with check (
    actor_profile_id = (select auth.uid())
    and exists (
      select 1 from public.profiles
      where profiles.id = (select auth.uid()) and profiles.verification_status = 'verified'
    )
  );

-- External psychology-news cache, refreshed on-demand (read-through, TTL
-- checked whenever the Overview loads) rather than via a background cron -
-- there's no scheduled worker in this app, and the source feeds only need
-- checking once or twice a day per Nick's own call on freshness.
create table public.news_cache (
  id bigint generated by default as identity primary key,
  source_name text not null,
  title text not null,
  link text not null unique,
  published_at timestamptz,
  fetched_at timestamptz not null default now()
);

create index news_cache_published_at_idx on public.news_cache (published_at desc);

alter table public.news_cache enable row level security;

create policy "verified users can read news cache"
  on public.news_cache for select
  using (exists (
    select 1 from public.profiles
    where profiles.id = (select auth.uid()) and profiles.verification_status = 'verified'
  ));

create policy "verified users can refresh news cache"
  on public.news_cache for insert
  with check (exists (
    select 1 from public.profiles
    where profiles.id = (select auth.uid()) and profiles.verification_status = 'verified'
  ));

create policy "verified users can update news cache"
  on public.news_cache for update
  using (exists (
    select 1 from public.profiles
    where profiles.id = (select auth.uid()) and profiles.verification_status = 'verified'
  ))
  with check (exists (
    select 1 from public.profiles
    where profiles.id = (select auth.uid()) and profiles.verification_status = 'verified'
  ));
