-- A second, deliberately narrow user role: referring physicians/GPs who can
-- browse a read-only curated directory and send structured referrals, but
-- never see a psychologist's full profile, never appear in Network/
-- Messages/Town Hall/Caseload, and never message a member peer-to-peer.
-- Self-registers (like profiles), goes into 'pending' until an admin
-- approves it - the same reviewed-signup pattern as credential verification.
create table public.referring_providers (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  practice_name text,
  npi_number text,
  phone text,
  email text not null,
  approval_status text not null default 'pending' check (approval_status in ('pending', 'approved', 'rejected')),
  requested_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references public.profiles(id)
);

alter table public.referring_providers enable row level security;

create policy "a provider can register themselves"
  on public.referring_providers for insert
  with check (id = (select auth.uid()));

create policy "a provider can see their own registration"
  on public.referring_providers for select
  using (id = (select auth.uid()));

create policy "admins can see every provider registration"
  on public.referring_providers for select
  using (is_admin_user((select auth.uid())));

create policy "admins can review provider registrations"
  on public.referring_providers for update
  using (is_admin_user((select auth.uid())))
  with check (is_admin_user((select auth.uid())));

-- A single structured referral from an approved provider to one chosen
-- specialist - deliberately not free-form peer messaging. Only the
-- non-identifying essentials, no full patient name - this is a heads-up to
-- the specialist's office, not a clinical record.
create table public.provider_referrals (
  id bigint generated by default as identity primary key,
  referring_provider_id uuid not null references public.referring_providers(id) on delete cascade,
  target_profile_id uuid not null references public.profiles(id) on delete cascade,
  patient_initials text,
  patient_age_range text,
  reason text not null,
  urgency text not null default 'routine' check (urgency in ('routine', 'soon', 'urgent')),
  contact_details text not null,
  status text not null default 'sent' check (status in ('sent', 'acknowledged', 'declined')),
  status_note text,
  created_at timestamptz not null default now(),
  responded_at timestamptz
);

create index provider_referrals_target_profile_id_idx on public.provider_referrals (target_profile_id);
create index provider_referrals_referring_provider_id_idx on public.provider_referrals (referring_provider_id);

alter table public.provider_referrals enable row level security;

create policy "an approved provider can send a referral"
  on public.provider_referrals for insert
  with check (
    referring_provider_id = (select auth.uid())
    and exists (
      select 1 from public.referring_providers
      where referring_providers.id = (select auth.uid())
      and referring_providers.approval_status = 'approved'
    )
  );

create policy "a provider can see referrals they sent"
  on public.provider_referrals for select
  using (referring_provider_id = (select auth.uid()));

create policy "a specialist can see referrals sent to them"
  on public.provider_referrals for select
  using (target_profile_id = (select auth.uid()));

create policy "a specialist can acknowledge or decline their referrals"
  on public.provider_referrals for update
  using (target_profile_id = (select auth.uid()))
  with check (target_profile_id = (select auth.uid()));
