-- Practice Library (Product Spec v1): curated cards need a PA code, a plain
-- purpose line, a category, who it applies to and search tags. Populated for
-- the 20 starter resources from the starter set's manifest.csv.
alter table public.documents
  add column if not exists library_code text,
  add column if not exists summary text,
  add column if not exists category text,
  add column if not exists audience text,
  add column if not exists tags text[] not null default '{}';
create unique index if not exists documents_library_code_key on public.documents(library_code) where library_code is not null and owner_scope = 'world';

update public.documents set library_code='PA-01', summary='Two-clinician reciprocal coverage agreement with per-patient coverage summary and post-coverage debrief.', category='Coverage & Continuity', audience='Psychologists · Psychiatrists', tags=array['coverage','continuity of care','vacation coverage','ethics','agreement','private practice','group practice','psychology','psychiatry']::text[] where owner_scope='world' and title like 'PA-01:%';
update public.documents set library_code='PA-02', summary='Step-by-step plan and letter templates for stepping away from practice for more than two weeks without stranding patients.', category='Coverage & Continuity', audience='Psychologists · Psychiatrists', tags=array['extended leave','parental leave','medical leave','sabbatical','handoff','continuity of care','patient letters','caseload triage']::text[] where owner_scope='world' and title like 'PA-02:%';
update public.documents set library_code='PA-03', summary='Professional will template, practice continuity inventory, executor acceptance and consent-form language.', category='Coverage & Continuity', audience='Psychologists · Psychiatrists', tags=array['professional will','succession planning','incapacity','death of clinician','records custodian','practice closure','ethics','continuity of care']::text[] where owner_scope='world' and title like 'PA-03:%';
update public.documents set library_code='PA-04', summary='Charter, member agreement, 90-minute agenda, consultation log and quarterly health check for a peer consultation group.', category='Consultation & Collaboration', audience='Psychologists · Psychiatrists', tags=array['peer consultation','consultation group','confidentiality','ethics','case presentation','group charter','AI transcription']::text[] where owner_scope='world' and title like 'PA-04:%';
update public.documents set library_code='PA-05', summary='De-identified case presentation form, de-identification checklist, ethics decision steps and consultation response sheet.', category='Consultation & Collaboration', audience='Psychologists · Psychiatrists', tags=array['case consultation','case presentation','de-identification','ethics decision-making','peer consultation','treatment impasse','risk','medication question']::text[] where owner_scope='world' and title like 'PA-05:%';
update public.documents set library_code='PA-06', summary='Supervision agreement, session log and competency-based quarterly evaluation form for licensure, postdoctoral or consultative supervision.', category='Consultation & Collaboration', audience='Psychologists · Psychiatrists', tags=array['clinical supervision','postdoctoral supervision','licensure hours','supervisor','supervisee','evaluation','agreement','telesupervision']::text[] where owner_scope='world' and title like 'PA-06:%';
update public.documents set library_code='PA-07', summary='Referral, acceptance/decline and close-the-loop letters; six termination letter templates; discharge summary; records-request templates.', category='Coverage & Continuity', audience='Psychologists · Psychiatrists', tags=array['referral','termination','discharge summary','transfer of care','abandonment','records request','lost to follow-up','closing the loop']::text[] where owner_scope='world' and title like 'PA-07:%';
update public.documents set library_code='PA-08', summary='Prescriber–therapist collaboration agreement, patient acknowledgment and communication log for shared treatment.', category='Consultation & Collaboration', audience='Psychiatrists · Psychologists', tags=array['split treatment','collaborative care','psychiatrist','psychologist','medication management','communication','release of information','suicide risk']::text[] where owner_scope='world' and title like 'PA-08:%';
update public.documents set library_code='PA-09', summary='Adult psychotherapy informed consent with optional modules for couples/family, minors, assessment and group, plus a customization checklist.', category='Clinical Practice', audience='Psychologists · Psychiatrists', tags=array['informed consent','psychotherapy','confidentiality','limits of confidentiality','mandated reporting','onboarding','ethics']::text[] where owner_scope='world' and title like 'PA-09:%';
update public.documents set library_code='PA-10', summary='Telehealth consent addendum, location verification, pre-session checklist and multi-state licensure/PSYPACT decision flow.', category='Clinical Practice', audience='Psychologists · Psychiatrists', tags=array['telehealth','telepsychology','PSYPACT','interstate practice','licensure','informed consent','location verification','emergency plan']::text[] where owner_scope='world' and title like 'PA-10:%';
update public.documents set library_code='PA-11', summary='Patient consent for AI documentation tools, vendor due-diligence checklist, practice AI policy and AI-drafted note attestation.', category='Clinical Practice', audience='Psychologists · Psychiatrists', tags=array['AI','AI scribe','ambient documentation','consent','HIPAA','business associate agreement','recording','vendor vetting','documentation']::text[] where owner_scope='world' and title like 'PA-11:%';
update public.documents set library_code='PA-12', summary='Biopsychosocial intake, MSE, SMART treatment plan, SOAP/DAP/BIRP progress notes with examples, note-quality checklist and free measures reference.', category='Clinical Practice', audience='Psychologists · Psychiatrists', tags=array['documentation','progress notes','SOAP','DAP','BIRP','treatment plan','biopsychosocial','intake','psychotherapy notes','open notes','Cures Act','medical necessity']::text[] where owner_scope='world' and title like 'PA-12:%';
update public.documents set library_code='PA-13', summary='Risk formulation form, six-step safety plan (patient-facing), lethal means counseling guide, follow-up protocol, duty-to-protect state worksheet, and post-loss checklist.', category='Clinical Practice', audience='Psychologists · Psychiatrists', tags=array['suicide risk','safety plan','risk assessment','lethal means','duty to protect','crisis','988','follow-up','documentation','postvention']::text[] where owner_scope='world' and title like 'PA-13:%';
update public.documents set library_code='PA-14', summary='DEA telemedicine status and contingency plan, prescribing checklist, documentation elements, controlled-substance treatment agreement and patient notice letter.', category='Regulatory & Compliance', audience='Psychiatrists · Prescribing clinicians · Collaborating psychologists', tags=array['telepsychiatry','DEA','controlled substances','Ryan Haight','telemedicine','PDMP','EPCS','stimulants','benzodiazepines','buprenorphine','prescribing']::text[] where owner_scope='world' and title like 'PA-14:%';
update public.documents set library_code='PA-15', summary='Patient financial policy, Good Faith Estimate template with timing rules, superbill template with common codes, and a fee-setting worksheet.', category='Business & Practice Management', audience='Psychologists · Psychiatrists · Group practices', tags=array['financial policy','fees','good faith estimate','No Surprises Act','superbill','out-of-network','cancellation policy','CPT','self-pay','sliding scale']::text[] where owner_scope='world' and title like 'PA-15:%';
update public.documents set library_code='PA-16', summary='Model comparison, classification warning, term sheet, clause guide, onboarding checklist, and joint patient notice for a clinician departure.', category='Business & Practice Management', audience='Group practice owners · Clinicians joining a group · Psychologists · Psychiatrists', tags=array['group practice','independent contractor','employee','compensation','non-compete','non-solicitation','onboarding','credentialing','departure','patient notice','records custody']::text[] where owner_scope='world' and title like 'PA-16:%';
update public.documents set library_code='PA-17', summary='Model Notice of Privacy Practices, acknowledgment, HIPAA-compliant authorization forms (general and psychotherapy notes), records-request response letters, and a who-is-asking guide.', category='Regulatory & Compliance', audience='Psychologists · Psychiatrists · Group practices', tags=array['HIPAA','notice of privacy practices','release of information','authorization','right of access','psychotherapy notes','Part 2','records request','confidentiality','minors']::text[] where owner_scope='world' and title like 'PA-17:%';
update public.documents set library_code='PA-18', summary='Small-practice security risk analysis worksheet with example, safeguards checklist, business associate checklist, breach decision and notification guide, and incident log.', category='Regulatory & Compliance', audience='Psychologists · Psychiatrists · Group practices', tags=array['HIPAA','Security Rule','risk analysis','breach notification','ransomware','encryption','multi-factor authentication','business associate','incident response','cybersecurity']::text[] where owner_scope='world' and title like 'PA-18:%';
update public.documents set library_code='PA-19', summary='Master renewal tracker, annual compliance calendar, quarterly review agenda, and record retention and destruction log.', category='Regulatory & Compliance', audience='Psychologists · Psychiatrists · Group practices', tags=array['compliance','license renewal','CAQH','DEA','PSYPACT','continuing education','malpractice','record retention','destruction log','annual calendar']::text[] where owner_scope='world' and title like 'PA-19:%';
update public.documents set library_code='PA-20', summary='Decision table for subpoenas and legal requests, first-hour steps, intake log, letters to attorney and patient, treating-clinician role statement, and licensing board complaint checklist.', category='Regulatory & Compliance', audience='Psychologists · Psychiatrists · Group practices', tags=array['subpoena','court order','privilege','HIPAA','psychotherapy notes','Part 2','custody','testimony','forensic role','licensing board complaint','legal requests']::text[] where owner_scope='world' and title like 'PA-20:%';
